theme: minima
title: Always attempt to Simplify the Complex!
author: Sonia Verma
email: soniaverma1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This site is to showcase my technical writing work experience and my writing portfolio to future employers. I have made an attempt to include work samples from employers only if there are publically available. I have also included some additional samples of my writing that I created during my gratuate class (MS in Technical Communication Management) from Mercer University. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  sovetw # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
